language: python
dist: xenial
python:
  - "3.7"
before_install:
  - cd bin
  - pip install pylint
# Install dependencies
install:
  - pip install -r requirements.txt
script: 
  - pylint --disable=C,W --unsafe-load-any-extension=yes delete_lines.py
  - pylint --disable=W --unsafe-load-any-extension=yes flyboy_check_robotids.py
  - pylint --disable=C,W --unsafe-load-any-extension=yes update_dois.py
  - pylint --extension-pkg-whitelist=_mysql sync_flyf_initial_splits.py
