language: python
python:
  - "3.6"
before_install:
  - cd bin
# Install dependencies
install:
  - pip install -r requirements.txt
script: 
  - pylint --disable=C,W --extension-pkg-whitelist=_mysql delete_lines.py
  - pylint --disable=C,W --extension-pkg-whitelist=_mysql flyboy_check_robotids.py
  - pylint --disable=C,W --extension-pkg-whitelist=_mysql update_dois.py
