language: python
python:
  - "3.6"
before_install:
  - cd bin
# Install dependencies
install:
  - pip install -r requirements.txt
script: 
  - pylint --disable=C,W delete_lines.py
  - pylint --disable=C,W flyboy_check_robotids.py
  - pylint --disable=C,W update_dois.py
